// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnoGrdtLySFOBpJtRhIHjAsAXjnk3ybRg',
    appId: '1:144905320810:android:3c10b8963fe5b736800d13',
    messagingSenderId: '144905320810',
    projectId: 'social-sdu',
    storageBucket: 'social-sdu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkywn0fS7drLgyjrxtKC3CNcJ6m-uQ2X8',
    appId: '1:144905320810:ios:2990d342135caf67800d13',
    messagingSenderId: '144905320810',
    projectId: 'social-sdu',
    storageBucket: 'social-sdu.appspot.com',
    androidClientId: '144905320810-qcfu3ni61herule2l5sjhm14vv8ofqo3.apps.googleusercontent.com',
    iosClientId: '144905320810-stoavp5h1t7u03eicn3q1del3tlr0t8n.apps.googleusercontent.com',
    iosBundleId: 'com.example.youtubeClone',
  );
}
